
import time


from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.select import Select
from selenium.webdriver.common.by import By
from Face_Book.Basic_Test.Register_Locaters import *

# Run test while all register fields are null

def test_register_all_filed_null():
    driver = webdriver.Chrome()
    driver.get(facebook_url)
    driver.find_element(By.XPATH, registration_location).click()
    time.sleep(9)
    driver.find_element(By.XPATH, first_name_location).send_keys("")
    # first_name1.send_Key(Keys.RETURN)
    time.sleep(3)
    driver.find_element(By.XPATH, last_name_location).send_keys("")
    time.sleep(2)
    driver.find_element(By.XPATH, phone_or_email_location).send_keys("")
    time.sleep(2)
    driver.find_element(By.XPATH, reEmail_location).send_keys("")
    time.sleep(2)
    driver.find_element(By.XPATH, password_location).send_keys("")
    time.sleep(2)
    day_choose = Select(driver.find_element(By.XPATH, birthday_day_location))
    time.sleep(2)
    day_choose.select_by_value("")
    time.sleep(4)
    month_choose = Select(driver.find_element(By.ID , birthday_month_location))
    time.sleep(2)
    month_choose.select_by_visible_text("")
    time.sleep(2)
    year_choose = Select(driver.find_element(By.ID, birthday_year_location))
    time.sleep(2)
    year_choose.select_by_value("")
    time.sleep(2)
    # driver.find_element(By.XPATH, female_option_location).click()
    # time.sleep(2)
    driver.find_element(By.XPATH, male_option_location)
    time.sleep(2)
    driver.find_element(By.XPATH, custom_option_location)
    time.sleep(3)
    driver.find_element(By.XPATH, sign_up_button_location).click()
    time.sleep(3)
    driver.close()


# Run test when all fileds are valid

def test_register_all_filed_valid():
    driver = webdriver.Chrome()
    driver.get(facebook_url)
    driver.find_element(By.XPATH, registration_location).click()
    time.sleep(3)
    driver.find_element(By.XPATH, first_name_location).send_keys("Nadav")
    # first_name1.send_Key(Keys.RETURN)
    time.sleep(3)
    driver.find_element(By.XPATH, last_name_location).send_keys("Dan")
    time.sleep(2)
    driver.find_element(By.XPATH, phone_or_email_location).send_keys("sentayehutadesse233@gmail.com")
    time.sleep(2)
    driver.find_element(By.XPATH, reEmail_location).send_keys("sentayehutadesse233@gmail.com")
    time.sleep(2)
    driver.find_element(By.XPATH, password_location).send_keys("sente1234")
    time.sleep(2)
    day_choose = Select(driver.find_element(By.XPATH, birthday_day_location))
    time.sleep(2)
    day_choose.select_by_value("11")
    time.sleep(4)
    month_choose = Select(driver.find_element(By.ID , birthday_month_location))
    time.sleep(2)
    month_choose.select_by_visible_text("Feb")
    time.sleep(2)
    year_choose = Select(driver.find_element(By.ID, birthday_year_location))
    time.sleep(2)
    year_choose.select_by_value("2001")
    time.sleep(2)
    driver.find_element(By.XPATH, female_option_location).click()
    time.sleep(2)
    driver.find_element(By.XPATH, male_option_location).click()
    time.sleep(2)
    # driver.find_element(By.XPATH, custom_option_location).click()
    # time.sleep(3)
    driver.find_element(By.XPATH, sign_up_button_location).click()
    time.sleep(3)
    driver.close()

# Run test when all reqiured filds are valid

def test_register_required_filed_valid():
    driver = webdriver.Chrome()
    driver.get(facebook_url)
    driver.find_element(By.XPATH, registration_location).click()
    time.sleep(3)
    driver.find_element(By.XPATH, first_name_location).send_keys("")
    # first_name1.send_Key(Keys.RETURN)
    time.sleep(3)
    driver.find_element(By.XPATH, last_name_location).send_keys("")
    time.sleep(2)
    driver.find_element(By.XPATH, phone_or_email_location).send_keys("tadessesentayehu@gmail.com")
    time.sleep(2)
    driver.find_element(By.XPATH, reEmail_location).send_keys("tadessesentayehu@gmail.com")
    time.sleep(2)
    driver.find_element(By.XPATH, password_location).send_keys("gvghbhjbhj")
    time.sleep(2)
    day_choose = Select(driver.find_element(By.XPATH, birthday_day_location))
    time.sleep(2)
    day_choose.select_by_value("11")
    time.sleep(4)
    month_choose = Select(driver.find_element(By.ID , birthday_month_location))
    time.sleep(2)
    month_choose.select_by_visible_text("Feb")
    time.sleep(2)
    year_choose = Select(driver.find_element(By.ID, birthday_year_location))
    time.sleep(2)
    year_choose.select_by_value("2001")
    time.sleep(2)
    driver.find_element(By.XPATH, female_option_location).click()
    time.sleep(2)
    driver.find_element(By.XPATH, male_option_location).click()
    time.sleep(2)
    # driver.find_element(By.XPATH, custom_option_location).click()
    # time.sleep(3)
    driver.find_element(By.XPATH, sign_up_button_location).click()
    time.sleep(3)
    driver.find_element(By.XPATH, result_location)
    time.sleep(4)
    driver.close()

#Run test when invalid email

def test_register_invalid_email():
    driver = webdriver.Chrome()
    driver.get(facebook_url)
    driver.find_element(By.XPATH, registration_location).click()
    time.sleep(3)
    driver.find_element(By.XPATH, first_name_location).send_keys("Asaf")
    time.sleep(3)
    driver.find_element(By.XPATH, last_name_location).send_keys("Levi")
    time.sleep(2)
    driver.find_element(By.XPATH, phone_or_email_location).send_keys("tadessesentay4.com")
    time.sleep(2)
    driver.find_element(By.XPATH, reEmail_location).send_keys("tadessesentay4.com")
    time.sleep(2)
    driver.find_element(By.XPATH, password_location).send_keys("gvghbhjbhj")
    time.sleep(2)
    day_choose = Select(driver.find_element(By.XPATH, birthday_day_location))
    time.sleep(2)
    day_choose.select_by_value("11")
    time.sleep(4)
    month_choose = Select(driver.find_element(By.ID , birthday_month_location))
    time.sleep(2)
    month_choose.select_by_visible_text("Feb")
    time.sleep(2)
    year_choose = Select(driver.find_element(By.ID, birthday_year_location))
    time.sleep(2)
    year_choose.select_by_value("2001")
    time.sleep(2)
    driver.find_element(By.XPATH, female_option_location).click()
    time.sleep(2)
    driver.find_element(By.XPATH, male_option_location).click()
    time.sleep(2)
    # driver.find_element(By.XPATH, custom_option_location).click()
    # time.sleep(3)
    driver.find_element(By.XPATH, sign_up_button_location).click()
    time.sleep(3)
    driver.find_element(By.XPATH, result_location)
    time.sleep(4)
    driver.close()

# Run test when re enter email invalid

def test_register_wrong_reEnter_email():
    driver = webdriver.Chrome()
    driver.get(facebook_url)
    driver.find_element(By.XPATH, registration_location).click()
    time.sleep(3)
    driver.find_element(By.XPATH, first_name_location).send_keys("Jacobdd")
    # first_name1.send_Key(Keys.RETURN)
    time.sleep(3)
    driver.find_element(By.XPATH, last_name_location).send_keys("Fordf")
    time.sleep(2)
    driver.find_element(By.XPATH, phone_or_email_location).send_keys("tadessesentayehu233@gmail.com")
    time.sleep(2)
    driver.find_element(By.XPATH, reEmail_location).send_keys("tadessesentay.com")
    time.sleep(2)
    driver.find_element(By.XPATH, password_location).send_keys("gvghbhjbhj")
    time.sleep(2)
    day_choose = Select(driver.find_element(By.XPATH, birthday_day_location))
    time.sleep(2)
    day_choose.select_by_value("11")
    time.sleep(4)
    month_choose = Select(driver.find_element(By.ID , birthday_month_location))
    time.sleep(2)
    month_choose.select_by_visible_text("Feb")
    time.sleep(2)
    year_choose = Select(driver.find_element(By.ID, birthday_year_location))
    time.sleep(2)
    year_choose.select_by_value("2001")
    time.sleep(2)
    driver.find_element(By.XPATH, female_option_location).click()
    time.sleep(2)
    driver.find_element(By.XPATH, male_option_location).click()
    time.sleep(2)
    # driver.find_element(By.XPATH, custom_option_location).click()
    # time.sleep(3)
    driver.find_element(By.XPATH, sign_up_button_location).click()
    time.sleep(3)
    driver.find_element(By.XPATH, result_location)
    time.sleep(4)
    driver.close()

# Run test when re enter email valid and email invalid

def test_register_reEnter_email_valid():
    driver = webdriver.Chrome()
    driver.get(facebook_url)
    driver.find_element(By.XPATH, registration_location).click()
    time.sleep(3)
    driver.find_element(By.XPATH, first_name_location).send_keys("Jacob")
    # first_name1.send_Key(Keys.RETURN)
    time.sleep(3)
    driver.find_element(By.XPATH, last_name_location).send_keys("Ford")
    time.sleep(2)
    driver.find_element(By.XPATH, phone_or_email_location).send_keys("tadessesentayehu.com")
    time.sleep(2)
    driver.find_element(By.XPATH, reEmail_location).send_keys("tadessesentayehu4355@gmail.com")
    time.sleep(2)
    driver.find_element(By.XPATH, password_location).send_keys("gvghbhjbhj")
    time.sleep(2)
    day_choose = Select(driver.find_element(By.XPATH, birthday_day_location))
    time.sleep(2)
    day_choose.select_by_value("11")
    time.sleep(4)
    month_choose = Select(driver.find_element(By.ID , birthday_month_location))
    time.sleep(2)
    month_choose.select_by_visible_text("Feb")
    time.sleep(2)
    year_choose = Select(driver.find_element(By.ID, birthday_year_location))
    time.sleep(2)
    year_choose.select_by_value("2001")
    time.sleep(2)
    driver.find_element(By.XPATH, female_option_location).click()
    time.sleep(2)
    driver.find_element(By.XPATH, male_option_location).click()
    time.sleep(2)
    # driver.find_element(By.XPATH, custom_option_location).click()
    # time.sleep(3)
    driver.find_element(By.XPATH, sign_up_button_location).click()
    time.sleep(3)
    driver.find_element(By.XPATH, result_location)
    time.sleep(4)
    driver.close()



# Run test when the email is not exist but have stracture of email

def test_register_not_existing_email():
    driver = webdriver.Chrome()
    driver.get(facebook_url)
    driver.find_element(By.XPATH, registration_location).click()
    time.sleep(3)
    driver.find_element(By.XPATH, first_name_location).send_keys("Jacob")
    # first_name1.send_Key(Keys.RETURN)
    time.sleep(3)
    driver.find_element(By.XPATH, last_name_location).send_keys("Ford")
    time.sleep(2)
    driver.find_element(By.XPATH, phone_or_email_location).send_keys("tadessesentayehu7773425@gmail.com")
    time.sleep(2)
    driver.find_element(By.XPATH, reEmail_location).send_keys("tadessesentayehu7773425@gmail.com")
    time.sleep(2)
    driver.find_element(By.XPATH, password_location).send_keys("gvghbhjbhj")
    time.sleep(2)
    day_choose = Select(driver.find_element(By.XPATH, birthday_day_location))
    time.sleep(2)
    day_choose.select_by_value("11")
    time.sleep(4)
    month_choose = Select(driver.find_element(By.ID , birthday_month_location))
    time.sleep(2)
    month_choose.select_by_visible_text("Feb")
    time.sleep(2)
    year_choose = Select(driver.find_element(By.ID, birthday_year_location))
    time.sleep(2)
    year_choose.select_by_value("2001")
    time.sleep(2)
    driver.find_element(By.XPATH, female_option_location).click()
    time.sleep(2)
    driver.find_element(By.XPATH, male_option_location).click()
    time.sleep(2)
    # driver.find_element(By.XPATH, custom_option_location).click()
    # time.sleep(3)
    driver.find_element(By.XPATH, sign_up_button_location).click()
    time.sleep(3)
    driver.find_element(By.XPATH, result_location)
    time.sleep(4)
    driver.close()


# Run test with no secure short length password

def test_register_short_password():
    driver = webdriver.Chrome()
    driver.get(facebook_url)
    driver.find_element(By.XPATH, registration_location).click()
    time.sleep(3)
    driver.find_element(By.XPATH, first_name_location).send_keys("Abrham")
    # first_name1.send_Key(Keys.RETURN)
    time.sleep(3)
    driver.find_element(By.XPATH, last_name_location).send_keys("Shalom")
    time.sleep(2)
    driver.find_element(By.XPATH, phone_or_email_location).send_keys("tadessesentayehu654@gmail.com")
    time.sleep(2)
    driver.find_element(By.XPATH, reEmail_location).send_keys("tadessesentayehu654@gmail.com")
    time.sleep(2)
    driver.find_element(By.XPATH, password_location).send_keys("55d")
    time.sleep(2)
    day_choose = Select(driver.find_element(By.XPATH, birthday_day_location))
    time.sleep(2)
    day_choose.select_by_value("11")
    time.sleep(4)
    month_choose = Select(driver.find_element(By.ID , birthday_month_location))
    time.sleep(2)
    month_choose.select_by_visible_text("Feb")
    time.sleep(2)
    year_choose = Select(driver.find_element(By.ID, birthday_year_location))
    time.sleep(2)
    year_choose.select_by_value("2001")
    time.sleep(2)
    driver.find_element(By.XPATH, female_option_location).click()
    time.sleep(2)
    driver.find_element(By.XPATH, male_option_location).click()
    time.sleep(2)
    # driver.find_element(By.XPATH, custom_option_location).click()
    # time.sleep(3)
    driver.find_element(By.XPATH, sign_up_button_location).click()
    time.sleep(3)
    password = driver.find_element(By.ID, error_password).text
    assert password != "reg_error_inner"
    time.sleep(4)
    driver.close()
